### ISSUE TITLE
Incorrect RBAC enforcement decorator

### ISSUE THREAD

**Issue by cdabella** [anr007/airflow-xtended-api#3]
Containerized

Debian GNU/Linux 11 (bullseye)
Python 3.9.16
Airflow 2.5.3

The plugin fails to load because the API routes use the incorrect decorator to enforce RBAC on the endpoints. You will see the following error in your Airflow logs.

```
RuntimeError: Working outside of application context.
 
 This typically means that you attempted to use functionality that needed
 the current application. To solve this, set up an application context
 with app.app_context(). See the documentation for more information.
```

The appropriate patch is to make the following changes to all files in `airflow_xtended_api/api/endpoints/*`

`from airflow.api_connexion import security` -> `from airflow.www.auth import has_access`

`@security.requires_access` -> `@has_access`

https://github.com/anr007/airflow-xtended-api/blob/a97e5c50959994403153273ce2a611a84467e1d1/airflow_xtended_api/api/endpoints/create_dag.py#L4

**Comment by anr007** [comment]
Thanks for highlighting this @cdabella! This bug has been fixed in the [v0.1.6](https://github.com/anr007/airflow-xtended-api/releases/tag/v0.1.6) release.
